temp:
  0:
    name: Light Banner
    t0: Bimini
disp:
  0:
    name: Unused
scl:
  0:
    name: Unused
pulse:
  0:
    name: Unused
    p0: Unused
    p0_wPerPulse: 0.25
bat:
  0:
    name: Unused
    s0: Unused
    v0: Rail
    v0_reference: true
    v1: Unused
air:
  0:
    name: Unused
inv: #inverters
  0:
    name: Unused
bee:
  0:
bms:
  0:
    name: Unused
  1:
    name: Main Battery
svc:
  0:
    name: SevCon
gps:
  0:
    name: Enchantee-GPS
  1:
    name: RaspPi-GPS
pth:
  0:
    name: Enchantee-Pressure
mwv:
  0:
    name: Anemometer
imu:
  0:
    name: IMU Sensor

