version: '2'
services:
  influxdb:
    image: arm32v7/influxdb:latest
    container_name: influx
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
      - /share/influxdb/influxdb_backup:/backups
    environment:
      - INFLUXDB_DB=sensors
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_HTTP_FLUX_ENABLED=true
    restart: always

  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - 1883:1883
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/logs
      - ./mosquitto-config:/mosquitto/config
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana1
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_PANELS_ENABLE_ALPHA=true
      - GF_SERVER_ROOT_URL=${GRAFANA_URL}
      - GF_ALLOW_UI_UPDATES=true
      - GF_ALLOWUIUPDATES=true
    restart: always

volumes:
  influxdb-storage:
  grafana-storage:
  mosquitto-data:
  mosquitto-logs:
  mosquitto-conf:
