services:
  influxdb:
    image: arm32v7/influxdb:latest
    container_name: influx
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
      - /share/influxdb/influxdb_backup:/backups
    environment:
      - INFLUXDB_DB=sensors
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_HTTP_FLUX_ENABLED=true
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana1
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_PANELS_ENABLE_ALPHA=true
      - GF_SERVER_ROOT_URL=${GRAFANA_URL}
      - GF_SERVER_DOMAIN=${DOMAIN_NAME}
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
    restart: always

  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - 1883:1883
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/logs
      - ./mosquitto-config:/mosquitto/config
    restart: always

  emon_mqtt_to_log:
    image: sfewings32/emon_mqtt_to_log:date_settings
    container_name: emon_log
    volumes:
      - /share/Input:/share/Input
    depends_on:
      - mosquitto
    environment:
      - MQTT_IP=mqtt
      - TZ=${TIMEZONE}
    restart: always

  emon_gpsd_to_mqtt:
    image: sfewings32/emon_gpsd_to_mqtt:date_settings
    container_name: emon_gpsd
    # Use host network to access the gpsd service that should be running. Then set MQTT_IP to localhost instead of mqtt
    network_mode: "host"    
    volumes:
      - ./emon_config:/data
      - /share/Input:/share/Input
    environment:
      - SETTINGS_PATH=/data/emon_config.yml
      - LOG_PATH=/share/Input/gps
      - MQTT_IP=localhost
      - GPS_NODE_NUMBER=1
      - TZ=${TIMEZONE}
    depends_on:
      - mosquitto
    restart: always

  emon_serial_to_mqtt:
    image: sfewings32/emon_serial_to_mqtt:date_settings
    container_name: emon_serial
    devices:
      - /dev/ttyAMA0  #/dev/ttyUSB0
    environment:
      - SETTINGS_PATH=/data/emon_config.yml
      - SERIAL_PORT=/dev/ttyAMA0   #/dev/ttyUSB0
      - MQTT_IP=mqtt
      - TZ=${TIMEZONE}
    volumes:
      - ./emon_config:/data
      - /share/Output:/share/Output
    depends_on:
      - mosquitto
    restart: always

  emon_mqtt_to_influx:
    image: sfewings32/emon_mqtt_to_influx:date_settings
    container_name: emon_influx
    volumes:
      - ./emon_config:/share/config
    environment:
      - MQTT_IP=mqtt
      - INFLUX_IP=influxdb
      - SETTINGS_PATH=/share/config/emon_config.yml
    depends_on:
      - influxdb
      - mosquitto
    restart: always

  emon_settings_web:
    image: sfewings32/emon_settings_web:date_settings
    container_name: emon_settings_web
    ports:
      - '5000:5000'
    volumes:
      - ./emon_config:/config
    environment:
      - EMON_CONFIG=/config
      - TZ=${TIMEZONE}
      - FLASK_APP=emon_settings_web.py
    restart: unless-stopped

  node-red:
    image: nodered/node-red:latest
    container_name: node_red
    environment:
      - TZ=${TIMEZONE}
    entrypoint: /data/entrypoint.sh
    ports:
      - "1880:1880"
    volumes:
      - /share/emon-node-red:/data
      - /share:/share
      - /media:/containermedia
    depends_on:
      - mosquitto
    restart: always

  emon_logtojson:
    image: sfewings32/emon_logtojson:latest
    container_name: emon_logtojson
    volumes:
      - /share:/share
    environment:
      - TZ=${TIMEZONE}
      - MQTT_IP=mqtt
      - REPROCESS_LOGS_FROM_YEAR=this
    depends_on:
      - mosquitto
    restart: always

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-data:/data
    ports:
      - 9000:9000
      - 9443:9443


volumes:
  influxdb-storage:
  grafana-storage:
  mosquitto-data:
  mosquitto-logs:
  mosquitto-conf:
  portainer-data:
